version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/contract-tests"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/example"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/launchdarkly-android-client-sdk"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/shared-test-code"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
