name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  run_tests:
    description: 'If true, run unit tests, otherwise skip them.'
    required: false
    default: 'true'
  android_api_level:
    description: 'The Android API level to use.'
    required: true
  java_version:
    description: 'The Java version to use.'
    required: true
  java_distribution:
    description: 'The Java distribution to use.'
    required: false
    default: 'temurin'

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build
      shell: bash
      id: build
      run: ./gradlew build jar

#    - name: Run Unit Tests
#      if: inputs.run_tests == 'true'
#      shell: bash
#      run: ./gradlew test
#
#    - name: Build contract tests
#      shell: bash
#      run: make build-contract-tests

    - name: Perform Instrumented Tests
      uses: reactivecircus/android-emulator-runner@6b0df4b0efb23bb0ec63d881db79aefbc976e4b2 #2.30.1
      with:
        api-level: ${{ inputs.android_api_level }}
        target: google_apis
        emulator-boot-timeout: 900
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: |
#          make start-contract-test-service
#          make run-contract-tests
          ./gradlew connectedDebugAndroidTest

    - name: Build documentation
      uses: ./.github/actions/build-docs
